
package Vistas;

import controlador.Controlador_editorial;
import javax.swing.JOptionPane;
import modelo.Modelo_editorial;
/**
 *
 * @author Franklin Aguirre
 */
public class Vista_editorial extends javax.swing.JFrame {
    Controlador_editorial controlador_editorial;
    /**
     * Creates new form Vista_editorial
     */
    public Vista_editorial() {
        initComponents();
        controlador_editorial= new Controlador_editorial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinalizar = new javax.swing.JButton();
        txtpais_de_origen_editorial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtpagina_web_editorial = new javax.swing.JTextField();
        lblNombreRecurso = new javax.swing.JLabel();
        txtnombre_editorial = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtcodigo_editorial = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFinalizar.setBackground(new java.awt.Color(255, 0, 51));
        btnFinalizar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setBorderPainted(false);
        btnFinalizar.setFocusable(false);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        txtpais_de_origen_editorial.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Pais de origen:");

        lblAutor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblAutor.setText("Pagina web:");

        txtpagina_web_editorial.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        lblNombreRecurso.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreRecurso.setText("Nombre:");

        txtnombre_editorial.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        lblCodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCodigo.setText("Codigo:");

        txtcodigo_editorial.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(255, 0, 51));
        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(255, 0, 51));
        btnActualizar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 0, 51));
        btnAgregar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setFocusable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombreRecurso)
                    .addComponent(lblAutor)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpagina_web_editorial, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtpais_de_origen_editorial)
                    .addComponent(txtnombre_editorial)
                    .addComponent(txtcodigo_editorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(542, Short.MAX_VALUE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtcodigo_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRecurso)
                    .addComponent(txtnombre_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpagina_web_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpais_de_origen_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 320, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(377, 377, 377)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        System.out.println("Se presiono el boton buscar");
        
        String codigo = txtcodigo_editorial.getText();
                        
        try {
            Modelo_editorial modelo_editorial = controlador_editorial.consultar_editorial(codigo);

            txtnombre_editorial.setText(modelo_editorial.getNombre_editorial());
            txtpagina_web_editorial.setText(modelo_editorial.getPagina_web_editorial());
            txtpais_de_origen_editorial.setText(modelo_editorial.getPais_de_origen_editorial());

            System.out.println("Consulta exitosa");

        }
        catch (Exception e){
            System.out.println("F");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String codigo_editorial, nombre_editorial, pagina_web_editorial,pais_de_origen_editorial; 
       
        codigo_editorial = txtcodigo_editorial.getText();
        nombre_editorial = txtnombre_editorial.getText();
        pagina_web_editorial = txtpagina_web_editorial.getText();
        pais_de_origen_editorial = txtpais_de_origen_editorial.getText();
       
        try{
           controlador_editorial.insertar_editorial(codigo_editorial, nombre_editorial, pagina_web_editorial, pais_de_origen_editorial);
//           AREA.append("Editorial guardado exitosamente");
           //JOptionPane.showMessageDialog(null, "Programa guardado exitosamente");
           limpiarGUI();
          
        }
        catch(Exception e){
            //System.out.print ("Error al tratar de guardar un programa");
//            AREA.append("Error al tratar de guardar una Editorial");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtcodigo_editorial.getText();
    
    try {
        controlador_editorial.eliminar_editorial(codigo);
//        AREA.append("Se eliminó el registro correctamente");
        limpiarGUI();
    } catch (Exception e) {
//        AREA.append("Error al tratar de eliminar la Editorial");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        String codigo_editorial, nombre_editorial, pagina_web_editorial, pais_de_origen_editorial; 
       
        codigo_editorial = txtcodigo_editorial.getText();
        nombre_editorial = txtnombre_editorial.getText();
        pagina_web_editorial = txtpagina_web_editorial.getText();
        pais_de_origen_editorial = txtpais_de_origen_editorial.getText();
        
        
        Modelo_editorial modelo_editorial = new Modelo_editorial(); 
        
        modelo_editorial.setCodigo_editorial(codigo_editorial);
        modelo_editorial.setNombre_editorial(nombre_editorial);
        modelo_editorial.setPagina_web_editorial(pagina_web_editorial);
        modelo_editorial.setPais_de_origen_editorial(pais_de_origen_editorial);


        try{

            if (!"".equals(nombre_editorial)){
                controlador_editorial.modificar_editorial(modelo_editorial, "nombre_editorial", nombre_editorial);
            }

            if (!"".equals(pagina_web_editorial)){
                controlador_editorial.modificar_editorial(modelo_editorial, "pagina_web_editorial", pagina_web_editorial);
            }

            if (!"".equals(pais_de_origen_editorial)){
                controlador_editorial.modificar_editorial(modelo_editorial, "pais_de_origen_editorial", pais_de_origen_editorial);
            }
                
        } catch(Exception e){
        }   
        
        limpiarGUI();
    }//GEN-LAST:event_btnActualizarActionPerformed
   private void limpiarGUI(){
        txtcodigo_editorial.setText("");
        txtnombre_editorial.setText("");
        txtpagina_web_editorial.setText("");
        txtpais_de_origen_editorial.setText("");
       
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombreRecurso;
    public javax.swing.JTextField txtcodigo_editorial;
    public javax.swing.JTextField txtnombre_editorial;
    public javax.swing.JTextField txtpagina_web_editorial;
    public javax.swing.JTextField txtpais_de_origen_editorial;
    // End of variables declaration//GEN-END:variables
}
